apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lifemonitor-web.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
    helm.sh/chart: {{ include "lifemonitor-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json : |-
    {
        "apiBaseUrl": "https://{{ .Values.externalServerName }}/api",
        "appDomain": "{{ .Values.externalServerName }}",
        "socketBaseUrl": "https://{{ .Values.externalServerName }}"
        {{- if .Values.backend.clientId }}, "clientId": "{{ .Values.backend.clientId }}"{{ end }}
        {{- if .Values.maintenanceMode.enabled }}, "maintenanceMode": "true"{{ end }}
        {{- if .Values.maintenanceMode.message }}, "maintenanceMessage":"{{.Values.maintenanceMode.message}}"{{ end }}
    }
