apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lifemonitor-web.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
    helm.sh/chart: {{ include "lifemonitor-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json : |-
    {
        "apiBaseUrl": "https://{{ .Values.externalServerName }}/api",
        "socketBaseUrl": "https://{{ .Values.externalServerName }}",
        "clientId": "{{ .Values.backend.clientId }}"
    }
