apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lifemonitor-web.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lifemonitor-web.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      helm.sh/chart: {{ include "lifemonitor-web.chart" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "lifemonitor-web.chart" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
          {{- if .Values.monitoring.enabled }}
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- end }}
          volumeMounts:
            - name: frontend-config
              mountPath: /app/assets/config.json
              subPath: config.json
            - name: nginx-config
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/webapp.prod.conf
              subPath: app.conf
            - name: nginx-logs
              mountPath: /var/log/nginx
            - name: nginx-run
              mountPath: /var/run/nginx
            {{ if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.monitoring.enabled }}
        - name: promtail
          image: grafana/promtail:master
          args:
            - "-config.file=/etc/promtail/promtail.yaml" # Found in the ConfigMap
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: nginx-logs
              mountPath: /var/log/nginx
        {{- end }}
      volumes:
        - name: frontend-config
          configMap:
            name: {{ include "lifemonitor-web.fullname" . }}-frontend-config
            defaultMode: 0644
        - name: nginx-config
          configMap:
            name: {{ include "lifemonitor-web.fullname" . }}-nginx-config
            defaultMode: 0644
        - name: nginx-logs
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        {{- if .Values.monitoring.enabled }}
        - name: promtail-config
          configMap:
            name: {{ include "lifemonitor-web.fullname" . }}-promtail-configmap
            defaultMode: 0644
        {{- end }}
        {{ if .Values.extraVolumes }}
          {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
