# Copyright (c) 2020-2024 CRS4
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
{{- if .Values.monitoring.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: '9090'
  labels:
    app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
  name: {{ .Release.Name }}-frontend-proxy-metrics-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lifemonitor-web.chart" . }}
  ports:
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090

---

{{- if .Values.monitoring.servicemonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lifemonitor-web.name" . }}-metrics-servicemonitor
  # same namespace that Prometheus is running in
  namespace: {{ .Values.monitoring.prometheus.namespace }}
  labels:
    app: {{ include "lifemonitor-web.name" . }}
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
  endpoints:
    - path: /metrics
      port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }} # namespace where the app is running
{{- end -}} # end if .Values.monitoring.servicemonitor.enabled
{{- end -}} # end if .Values.monitoring.enabled

