{{- if .Values.monitoring.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: '9090'
  labels:
    app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
  name: {{ .Release.Name }}-frontend-proxy-metrics-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lifemonitor-web.chart" . }}
  ports:
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090

---

{{- if .Values.monitoring.servicemonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lifemonitor-web.name" . }}-metrics-servicemonitor
  # same namespace that Prometheus is running in
  namespace: {{ .Values.monitoring.prometheus.namespace }}
  labels:
    app: {{ include "lifemonitor-web.name" . }}
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lifemonitor-web.name" . }}
  endpoints:
    - path: /metrics
      port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }} # namespace where the app is running
{{- end -}} # end if .Values.monitoring.servicemonitor.enabled
{{- end -}} # end if .Values.monitoring.enabled

